server:
  port: 20001
spring:
  datasource:
    url: jdbc:mysql://119.23.32.163:3306/mirrorego_game?useSSL=false
    username: gamer
    password: Gm123@2022#456
logging:
  level:
    root: info
    com:
      example:
        area:
          areabackend: info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml